//! Exercise the *other* half of the legacy-contract machinery: the
//! `build.rs` registry reader that turns `legacy_contracts.toml` into
//! the `LEGACY_REPO_CONTRACT_WASM_HASHES` const the client walks.
//!
//! `tests/legacy_fallback.rs` covers what happens once a hash is in
//! that array. This file covers how a hash gets there. Both halves
//! matter and neither has ever run for real: the shipped registry has
//! contained zero `[[entry]]` blocks since it was introduced, so the
//! hand-rolled TOML parser has never parsed an entry and the code
//! generator has never emitted one.
//!
//! The registry is parsed at compile time, so a mistake here is a
//! mistake baked into every published binary — and it would surface
//! only on the first real re-key, which is exactly when users' repos
//! depend on it.

#[allow(dead_code)]
#[path = "../build.rs"]
mod build_script;

use build_script::{generate_code, parse_legacy_entries};
use freenet_stdlib::prelude::{ContractCode, ContractInstanceId, Parameters};

/// Synthetic stand-in for a previously-shipped repo-contract WASM.
fn synthetic_wasm(tag: u8) -> Vec<u8> {
    let mut bytes = b"\0asm\x01\0\0\0synthetic-repo-contract-".to_vec();
    bytes.extend(std::iter::repeat_n(tag, 512));
    bytes
}

fn hex_of(bytes: &[u8; 32]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Pull the `[u8; 32]` literals back out of the generated Rust source.
///
/// Reading the emitted text rather than trusting `Entry.wasm_hash` is
/// the point: the parser could be perfect while the generator emitted
/// the bytes reversed, truncated, or in the wrong entry, and nothing
/// downstream would notice until a migration probed a key that has
/// never existed.
fn extract_generated_hashes(generated: &str) -> Vec<[u8; 32]> {
    let mut out = Vec::new();
    for line in generated.lines() {
        // Entry lines look like `    (&[0x00, 0x01, …], "desc"),`.
        // The type declaration also contains `(&[`, so match on the
        // indented entry form rather than the substring alone.
        let Some(rest) = line.trim_start().strip_prefix("(&[") else {
            continue;
        };
        if !line.starts_with("    ") {
            continue;
        }
        let Some(end) = rest.find(']') else { continue };
        let mut bytes = Vec::new();
        for token in rest[..end].split(',') {
            let token = token.trim().trim_start_matches("0x");
            if token.is_empty() {
                continue;
            }
            bytes.push(u8::from_str_radix(token, 16).expect("generated byte literal is hex"));
        }
        let arr: [u8; 32] = bytes
            .try_into()
            .expect("generated array literal must be exactly 32 bytes");
        out.push(arr);
    }
    out
}

/// The whole chain, end to end: a hash written into
/// `legacy_contracts.toml` must come out of the generated code as the
/// same 32 bytes, and those bytes must derive the same contract key
/// that the predecessor WASM itself would have produced.
///
/// The final assertion is the one that matters. It compares against
/// `ContractInstanceId::from_params_and_code` over the original WASM —
/// the stdlib's own derivation — so a byte-order or truncation bug
/// anywhere in TOML → parse → codegen → `contract_id_from_wasm_hash`
/// shows up as a key mismatch rather than as a self-consistent pass.
#[test]
fn a_registry_entry_survives_the_trip_to_a_probeable_contract_key() {
    let legacy_wasm = synthetic_wasm(0x1E);
    let legacy_hash = *blake3::hash(&legacy_wasm).as_bytes();

    let toml = format!(
        "# a comment that must be ignored\n\
         [[entry]]\n\
         description = \"0.1.3 repo-contract\"\n\
         wasm_hash = \"{}\"\n",
        hex_of(&legacy_hash)
    );

    let entries = parse_legacy_entries(&toml);
    assert_eq!(entries.len(), 1, "one [[entry]] block must yield one entry");
    assert_eq!(entries[0].description, "0.1.3 repo-contract");
    assert_eq!(
        entries[0].wasm_hash, legacy_hash,
        "parsed hash must equal the hex written in the registry"
    );

    let generated = generate_code(&entries);
    let emitted = extract_generated_hashes(&generated);
    assert_eq!(emitted, vec![legacy_hash], "codegen must emit those bytes");
    assert!(
        generated.contains("\"0.1.3 repo-contract\""),
        "the description is what a migration log line prints; generated:\n{generated}"
    );

    // The payoff: the emitted bytes must address the same contract the
    // predecessor WASM did.
    let params = freenet_git_types::RepoParams {
        prefix: "abc1234567".to_string(),
    }
    .to_bytes();
    let from_registry = freenet_git_cli::wsclient::contract_id_from_wasm_hash(&emitted[0], &params);
    let from_wasm = ContractInstanceId::from_params_and_code(
        Parameters::from(params.clone()),
        ContractCode::from(legacy_wasm),
    );
    assert_eq!(
        from_registry, from_wasm,
        "a registry entry must probe the contract key the predecessor WASM actually had"
    );
}

/// Multiple entries keep their registry order and stay distinct.
/// `GetSource::Legacy { index }` indexes back into this array to name
/// the version in a log line, so a reordering or a collapsed duplicate
/// would mislabel — or, with `LEGACY_REPO_CONTRACT_WASM_HASHES[index]`,
/// panic.
#[test]
fn multiple_entries_keep_registry_order() {
    let hashes: Vec<[u8; 32]> = (0..3)
        .map(|i| *blake3::hash(&synthetic_wasm(0xA0 + i)).as_bytes())
        .collect();
    let mut toml = String::from("# registry\n");
    for (i, h) in hashes.iter().enumerate() {
        toml.push_str(&format!(
            "\n[[entry]]\ndescription = \"0.1.{i} repo-contract\"\nwasm_hash = \"{}\"\n",
            hex_of(h)
        ));
    }

    let entries = parse_legacy_entries(&toml);
    assert_eq!(entries.len(), 3);
    let emitted = extract_generated_hashes(&generate_code(&entries));
    assert_eq!(
        emitted, hashes,
        "generated array must preserve the order entries appear in the registry"
    );
}

/// The shipped registry is empty and must generate an empty array
/// rather than, say, a syntax error or a phantom entry. This is the
/// state every release so far has compiled, so it is also the
/// regression guard for "the parser tolerates a comments-only file".
#[test]
fn a_comments_only_registry_generates_an_empty_array() {
    let shipped = include_str!("../legacy_contracts.toml");
    let entries = parse_legacy_entries(shipped);
    assert!(
        entries.is_empty(),
        "the shipped registry has no [[entry]] blocks; if this fires, an entry \
         was added and the fallback is now live — good, but re-check the \
         migration path before releasing"
    );
    let generated = generate_code(&entries);
    assert!(generated.contains("LEGACY_REPO_CONTRACT_WASM_HASHES: &[(&[u8; 32], &str)] = &[\n];"));
}

/// A malformed entry must fail the build loudly. The dangerous
/// alternative is silently dropping it: the registry would look
/// populated, the binary would carry no such hash, and the migration
/// would quietly not happen.
#[test]
#[should_panic(expected = "missing wasm_hash")]
fn an_entry_without_a_hash_fails_the_build() {
    parse_legacy_entries("[[entry]]\ndescription = \"0.1.3 repo-contract\"\n");
}

/// Likewise for a hash that is not 32 bytes of hex — a truncated paste
/// is the realistic version of this mistake.
#[test]
#[should_panic(expected = "expected 64 hex chars")]
fn a_truncated_hash_fails_the_build() {
    parse_legacy_entries("[[entry]]\ndescription = \"oops\"\nwasm_hash = \"deadbeef\"\n");
}
